name: Build and Push Docker Image

on:
  push:
    branches: [main]

job:
  build-and-push:
    runs-on-ubuntu-latest

    steps:
      - name: checkout the repository
        uses: actions/checkout@v2

      - name: Docker build
        run: |
          hostnamectl